---

- name: Ensure firewalld is installed
  become: true
  package:
    name: firewalld
    state: latest
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database

- name: Ensure firewalld is started
  become: true
  systemd:
    name: firewalld
    state: started
    enabled: true
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database

- name: Enable quay firewalld ports
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: "public"
    permanent: true
    state: enabled
  with_items:
    - '443/tcp'
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database

- name: Enable quay config firewalld ports
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: "public"
    permanent: true
    state: enabled
  with_items:
    - '{{ quay_config_port }}/tcp'
  when: ( quay_config_mode | bool )
  tags:
    - quay
    - quay-config
    - quay-worker
    - redis
    - database
