---
# tasks file for quay-ansible

- name: "Create quay config directory"
  file:
    state: directory
    path: "{{ quay_root_dir }}/config"
  tags:
    - quay

- name: "Create extra_ca_certs directory"
  file:
    state: directory
    path: "{{ quay_root_dir }}/config/extra_ca_certs"
  tags:
    - quay

- name: "Create quay storage directory (when object storage is not available)"
  file:
    state: directory
    path: "{{ quay_root_dir }}/storage"
  tags:
    - quay

- name: Set runtime engine
  set_fact:
    runtime: "docker"
  when: (not podman)

- name: Configure podman
  include_tasks: tasks/podman-setup.yml
  when: ( podman )

- name: Configure docker
  include_tasks: tasks/docker-setup.yml
  when: (not podman)

- name: Configure firewall
  include_tasks: tasks/firewall-setup.yml

- name: Deploy postgres
  include_tasks: tasks/deploy-postgresql.yml
  when: ( not rds )

- name: Deploy redis
  include_tasks: tasks/deploy-redis.yml

- name: Start quay in config mode
  include_tasks: tasks/quay-config-mode.yml
  when: ( quay_config_mode )

- name: Deploy Certificates
  include_tasks: tasks/create-certificate.yml
  when: ( not quay_config_mode )

- name: Start clairv4
  include_tasks: tasks/quay-clair.yml
  when: ( not quay_config_mode )

- name: Start quay
  include_tasks: tasks/deploy-quay.yml
  when: ( not quay_config_mode )
